### ISSUE TITLE
这里的64卦的排列顺序貌似跟常见的变换表不同

### ISSUE THREAD

**Issue by obiscr** [lizongying/go-gua64#1]
https://github.com/lizongying/go-gua64/blob/0d676d1d273bed83294a7962be4b8935eea70fcb/gua64/gua64.go#L9

我这里绘制过一个 https://obiscr.com/iching

**Comment by lizongying** [comment]
是不一樣。順序是根據二進制的順序排列的,"--"是0，“——”是1，自下而上計算。比如“䷁”，可以認為0000’0000，“䷖”是0000‘0001。
